version: "3.9"
services:
    bot:
        container_name: discord_roulette
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        env_file: .env
        volumes:
            - .:/usr/src/app
    database:
        container_name: mongo
        image: mongo:4.2.22
        ports:
            - 27017:27017
        volumes:
            - ../mongo:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
