apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-changes
  namespace: repo-pipeline
spec:
  params:
    - name: sha
      type: string
    - name: repoURL
      type: string
  results:
    - name: changed
      description: Returns value only if changes were found
  steps:
    - name: check-changes
      image: bitnami/kubectl
      script: |
        #!/bin/sh
        cd usr
        git clone $(params.repoURL) repo
        cd repo
        git diff --no-commit-id --name-only -r $(params.sha)^1 >> changes.txt
        egrep '^\.cicd' changes.txt
        if egrep -q '^\.cicd' changes.txt
        then
          echo -n "Changes found" >> $(results.changed.path)
        else
          echo -n "Changes not found" >> $(results.changed.path)
        fi
        echo $(results.changed.path)
        cat $(results.changed.path)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yaml-updater
  namespace: repo-pipeline
spec:
  params:
    - name: sha
      type: string
    - name: repoURL
      type: string
  steps:
    - name: yaml-updater
      image: bitnami/kubectl
      script: |
        #!/bin/sh
        cd usr
        git clone $(params.repoURL) repo
        cd repo
        kubectl apply -f .cicd
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: update-cicd
  namespace: repo-pipeline
spec:
  params:
    - name: sha
      type: string
      description: "the SHA of the recently detected change"
    - name: repoURL
      type: string
      description: "the cloneURL that the change was detected in"
  tasks:
    - name: check-for-changes
      params:
        - name: sha
          value: $(params.sha)
        - name: repoURL
          value: $(params.repoURL)
      taskRef:
        name: check-changes
    - name: yaml-updater
      params:
        - name: sha
          value: $(params.sha)
        - name: repoURL
          value: $(params.repoURL)
      taskRef:
        name: yaml-updater
      when:
        - input: $(tasks.check-for-changes.results.changed)
          operator: notin
          values: ["Changes not found"]
---
apiVersion: polling.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: github-listener
  namespace: repo-pipeline
  labels:
    name: test
spec:
  url: https://github.com/holy-tech/discord-roulette.git
  ref: main
  frequency: 1m
  type: github
  pipelineRef:
    serviceAccountName: kubectl-user
    name: update-cicd
    namespace: repo-pipeline
    params:
      - name: sha
        expression: commit.sha
      - name: repoURL
        expression: repoURL
