apiVersion: polling.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: github-listener
  namespace: repo-pipeline
  labels:
    name: test
spec:
  url: https://github.com/holy-tech/discord-roulette.git
  ref: feat/cicd-test-lint
  frequency: 1m
  type: github
  pipelineRef:
    serviceAccountName: kubectl-user
    name: update-cicd
    namespace: repo-pipeline
    params:
      - name: sha
        expression: commit.sha
      - name: repoURL
        expression: repoURL
    workspaces:
      - name: repo
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi