apiVersion: v1
kind: Secret
metadata:
  name: docker-key
  namespace: repo-pipeline
  annotations:
    tekton.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: <cleartext non-encoded>
  password: <cleartext non-encoded>
