apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-changes
  namespace: repo-pipeline
spec:
  params:
    - name: sha
      type: string
  results:
    - name: changed
      description: Returns value only if changes were found
  workspaces:
    - name: repo
      description: Git repo cloned here
      mountPath: /usr/repo
  steps:
    - name: check-changes
      image: bitnami/kubectl
      script: |
        #!/bin/sh
        cd /usr/repo
        git diff --no-commit-id --name-only -r $(params.sha)^1 >> changes.txt
        egrep '^\.cicd' changes.txt
        if egrep -q '^\.cicd' changes.txt
        then
          echo -n "Changes found" >> $(results.changed.path)
        else
          echo -n "Changes not found" >> $(results.changed.path)
        fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yaml-updater
  namespace: repo-pipeline
spec:
  workspaces:
    - name: repo
      description: Git repo cloned here
      mountPath: /usr/repo
  steps:
    - name: yaml-updater
      image: bitnami/kubectl
      script: |
        #!/bin/sh
        cd /usr/repo
        kubectl apply -f .cicd/namespace.yaml
        kubectl apply -f .cicd/roles
        kubectl apply -f .cicd/tasks
        kubectl apply -f .cicd/pipelines
