apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: testing
  namespace: repo-pipeline
spec:
  params:
    - name: repoURL
      type: string
      description: Git repo url
  steps:
    - name: parse-url
      image: golang:1.19.0-buster
      script: |
        #!/bin/sh
        cd /usr/repo
        go test ./...
