apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: testing
  namespace: repo-pipeline
spec:
  steps:
    - name: parse-url
      image: golang:1.19.0-buster
      script: |
        #!/bin/sh
        cd /usr/repo
        go test ./...
  workspaces:
    - name: repo
      description: Git repo cloned here
      mountPath: /usr/repo