apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: parse-url
  namespace: repo-pipeline
spec:
  params:
    - name: repoURL
      type: string
      description: Git repo url
  steps:
    - name: parse-url
      image: alpine
      script: |
        #!/bin/sh
        echo -n $(params.repoURL) | sed 's/https:\/\///' > $(results.parsedURL.path)
  results:
    - name: parsedURL
      description: Returns parsed url for kamiko
