apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: update-docker
  namespace: repo-pipeline
spec:
  params:
    - name: repoURL
      type: string
      description: "the cloneURL that the change was detected in"
    - name: branch
      type: string
      description: "the branch to build dockerfile off of"
  tasks:
    - name: update-image
      params:
        - name: repoURL
          value: $(params.repoURL)
        - name: branch
          value: $(params.branch)
      taskRef:
        name: update-image
