apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: update-cicd
  namespace: repo-pipeline
spec:
  workspaces:
    - name: repo
  params:
    - name: sha
      type: string
      description: "the SHA of the recently detected change"
    - name: repoURL
      type: string
      description: "the cloneURL that the change was detected in"
  tasks:
    - name: testing
      taskRef:
        name: testing
      workspaces:
        - name: repo
          workspace: repo

    - name: check-for-changes
      params:
        - name: sha
          value: $(params.sha)
        - name: repoURL
          value: $(params.repoURL)
      taskRef:
        name: check-changes
      workspaces:
        - name: repo
          workspace: repo

    - name: yaml-updater
      params:
        - name: sha
          value: $(params.sha)
        - name: repoURL
          value: $(params.repoURL)
      taskRef:
        name: yaml-updater
      workspaces:
        - name: repo
          workspace: repo
      when:
        - input: $(tasks.check-for-changes.results.changed)
          operator: notin
          values: ["Changes not found"]

    - name: parse-url
      params:
        - name: repoURL
          value: $(params.repoURL)
      taskRef:
        name: parse-url

    - name: update-image
      params:
        - name: repoURL
          value: $(tasks.parse-url.results.parsedURL)
      taskRef:
        name: update-image
        