apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: update-cicd
  namespace: repo-pipeline
spec:
  params:
    - name: sha
      type: string
      description: "the SHA of the recently detected change"
    - name: repoURL
      type: string
      description: "the cloneURL that the change was detected in"
  tasks:
    - name: check-for-changes
      params:
        - name: sha
          value: $(params.sha)
        - name: repoURL
          value: $(params.repoURL)
      taskRef:
        name: check-changes
    - name: yaml-updater
      params:
        - name: sha
          value: $(params.sha)
        - name: repoURL
          value: $(params.repoURL)
      taskRef:
        name: yaml-updater
      when:
        - input: $(tasks.check-for-changes.results.changed)
          operator: notin
          values: ["Changes not found"]
    - name: update-image
      params:
        - name: repoURL
          value: $(params.repoURL.parseURL().host)$(params.repoURL.parseURL().path)
      taskRef:
        name: update-image
        